### ISSUE TITLE
Wrong notes in the list of chord types for minor 6th (and wrong enharmonic notes throughout the list)

### ISSUE THREAD

**Issue by Denis347** [ShacharHarshuv/open-ear#169]
Minor 6th is written as (C-D#-G-G#), however that is minor b6. Minor 6 should be (C-Eb-G-A).
In fact the minor third is written as D# in all those C chords, but it should be Eb. (Yes, it's enharmonic equivalent, but not correct). 
The same applies for other chords there, like for example the Diminished (C-Eb-Gb), or the Minor 7th (C-Eb-G-Bb).

**Comment by ShacharHarshuv** [comment]
Hey, thanks for bringing this to my attention! I changed the chord type name to "minor b6th" here: https://github.com/ShacharHarshuv/open-ear/pull/173
If I understood correctly, the chord symbol is still `m6`, right? I.e. for `Cm6` I need to play `C-bE-G-bA`.

Regarding the incorrect enharmonic spelling - you are absolutely correct. The problem was that I programmed the chords with intervals by semitones numbers, and then converted it to human-readable notes, which automatically preferred the sharp spelling. This is of course not a problem when only playing the notes, but it indeed misleading if displaying the note names to the user. I'll think of a way to fix it.

**Comment by Denis347** [comment]
Ah okay, right. I thought so, that it was some kind of automatic process that wrote all those sharp (incorrect) notes. Not sure if this is doable in any way, but a way to fix this would be to write out the scale, and then use those notes (scale degrees), and lower/raise them. So you have C D E F G A B scale, and minor chord is `1 b3 5`, so that would be `C Eb G`. (E is the third degree, and it is lowered).

For the minor6 chord, the `m6` chord symbol is `1 b3 5 6`, so `C-Eb-G-A`. 
`C-Eb-G-Ab` is `1 b3 5 b6`, which has symbol `m(b6)`

**Comment by ShacharHarshuv** [comment]
OK I've changed m6 to mb6 in here: https://github.com/ShacharHarshuv/open-ear/pull/173
I've also fixed the wrong spelling here: https://github.com/ShacharHarshuv/open-ear/pull/176
