### ISSUE TITLE
Show the key and notes

### ISSUE THREAD

**Issue by UnkindPartition** [ShacharHarshuv/open-ear#22]
Hi, great app!

I sometimes do ear training with an instrument, and these changes would make it much more convenient:

1. For note/chord in key exercises, always show what key we're in (e.g. E major)
2. For interval recognition and triad inversions, after the correct answer is shown, also show which notes were played (e.g. "Major 2nd: F-G")

Thanks a lot!

**Comment by ShacharHarshuv** [comment]
Sounds like a good idea to me.
We do need to think of how to do that design wise, since the exercises are basically implementation of the `IExercise` interface, we need to think of how to support both options in that interface. If you (or anyone else) wants to implement it, please post a suggestion for changes to IExercise before implementing so we can discuss.
