### ISSUE TITLE
Support Inversions (aka Slash Chords)

### ISSUE THREAD

**Issue by jtagcat** [ShacharHarshuv/open-ear#245]
The functions section only has chords such as I and I6 (first inversion). I also need to know the 2nd inversion (I64, IV64, V64).

Please add second inversions to the options.

**Comment by ShacharHarshuv** [comment]
I6 in OpenEar is not first inversion like in classical Roman Numerals. OpenEar uses a unique chord system that is a combination of Jazz Symbols and Roman Numerals. The reason is that the classical basso-continuous based numerals is not well supporting of more advanced chords that can be found in Jazz and other modern music. in Jazz, a 6th chord is a major chord with a 6 interval added. (I  believe that would be a 65 in basso continuo).

Supporting inversions is [in progress ](https://github.com/ShacharHarshuv/open-ear/pull/243) but complicated due to the vast variety of options that poses a UI challenge.

**Comment by jtagcat** [comment]
Tried it yesterday, and suspected something was up :) #247 could've helped me get on to it faster. Thanks for clarifying.

**Comment by ShacharHarshuv** [comment]
I replied on #247 - the short version is that I don't understand that ticket, and I don't understand how this could help here.

**Comment by ShacharHarshuv** [comment]
This is done by https://github.com/ShacharHarshuv/open-ear/pull/254
