### ISSUE TITLE
Short press answers

### ISSUE THREAD

**Issue by jtagcat** [ShacharHarshuv/open-ear#246]
Functions: While in the settings holding on roman numerals to select is fine, it gets in the way in exercises. It simply takes too much time (can't keep up answering while listening multiple in a row).

If possible, please organize the buttons so that a single press is possible for all answers.

**Comment by ShacharHarshuv** [comment]
This is impossible because I want to make the button position consistent no-matter what chord symbols were selected. 
Please note that when answering you don't need a long press - a quick press is good enough. In real music chords are changed pretty slowly compared to melody notes, so I believe that you should be able to slow the chords speed enough so that you can pick them on time, but it is still fast enough to cover more occurrences in real music.
