### ISSUE TITLE
Analysing chords / intervals

### ISSUE THREAD

**Issue by jtagcat** [ShacharHarshuv/open-ear#247]
When listening to chords or intervals, it is sometimes difficult to exactly identify what is in the harmonic mix. A contributing factor might be that the synths really do merge the sound together, or I'm just not good enough. App piano vs a better VST or a real piano: the latter two I can almost always and instantly hear the individual sounds of.

Integrating better VSTs is probably technically complex and may conflict with licensing.

I would request #195 4: hearing individual chords + switching from harmonic to melodic when tapping on an answer box.

Just listening and guessing until you start getting it right is wasteful. Analysing what is actually going on, and reasoning what you are hearing is much more reasonable, in my opinion.

**Comment by ShacharHarshuv** [comment]
I'm sorry but I don't understand what this ticket is about. You seem to be talking about many different things. Please open separate requests for each feature with a clear explanation of what is the desired improvement. 

> the latter two I can almost always and instantly hear the individual sounds of

So you're saying the sound synthesis (samples) is preventing you from being able to easily separate notes that you're hearing? Why is that? Is it because the vibrato / timing of the samples are too exact, is it because of stereo? Identifying the cause of this can help improve it. It's possible that creating minor variation in timing will do the trick, or maybe it's something in the samples themselves. 

> I would request https://github.com/ShacharHarshuv/open-ear/issues/195 4: hearing individual chords

Please see my comment in the original issue. If you still think it might be a good feature open a separate issue for it, so we can avoid duplicates. 

> Just listening and guessing until you start getting it right is wasteful. Analysing what is actually going on, and reasoning what you are hearing is much more reasonable, in my opinion.

Not sure what you are requesting here. It seems more like a general tip than a feature...?
