### ISSUE TITLE
Option to display notes in alphabetic notation instead of syllabic

### ISSUE THREAD

**Issue by regulrjoe** [ShacharHarshuv/open-ear#99]

**Comment by ShacharHarshuv** [comment]
The solfegge syllables (Do, Re, Mi) are commonly used to denote scale degrees, while the alphabetic notation (C, D, E) is commonly used to denote absolute pitches. The exercises I guess you are referring to - Scale Degrees identification - actually plays in a random key, so the first scale degree ("Do") is not always the "C" pitch. 
To use alphabetic notation, we need to either put the "real" absolute note names, which will defer from key to key (I believe it will be unnecessarily confusing) - or always denote it as if it was C major (I.e. first degree = C) - which I also believe to be confusing and also inaccurate. 

Because of that reasons I personally believe that it's not a good idea to support alphabetic notation in that exercise. (We can still discuss if you disagree)
However - it can be a good idea to support numbers (1, 2, 3 = Do Re Mi), if you're unused to the solfegge syllables.

**Comment by ShacharHarshuv** [comment]
I have merged this: https://github.com/ShacharHarshuv/open-ear/pull/111
which enables selection of numeric values instead of solfege syllables.

**Comment by ShacharHarshuv** [comment]
Closed this, as expalined above alphabetic notation is not commonly used to denote scale degrees (only absolute pitches)
